// AUTO-GENERATED by build_smart_env_config.js. DO NOT EDIT.
import smart_actions from '../src/collections/smart_actions.js';
import smart_chat_threads from '../src/collections/smart_chat_threads.js';
import { SmartAction } from '../src/items/smart_action.js';
import { SmartChatThread } from '../src/items/smart_chat_thread.js';
import { render as chat_component } from '../src/components/chat.js';
import { render as chat_context_reviewer_component } from '../src/components/chat_context_reviewer.js';
import { render as completion_component } from '../src/components/completion.js';
import { render as confirm_delete_component } from '../src/components/confirm_delete.js';
import { render as message_action_component } from '../src/components/message_action.js';
import { render as message_assistant_component } from '../src/components/message_assistant.js';
import { render as message_system_component } from '../src/components/message_system.js';
import { render as message_user_component } from '../src/components/message_user.js';
import { render as overlay_requires_settings_component } from '../src/components/overlay_requires_settings.js';
import { render as thread_component } from '../src/components/thread.js';

export const smart_env_config = {
  collections: {
    smart_actions,
    smart_chat_threads
  },
  item_types: {
    SmartAction,
    SmartChatThread
  },
  components: {
    chat: chat_component,
    chat_context_reviewer: chat_context_reviewer_component,
    completion: completion_component,
    confirm_delete: confirm_delete_component,
    message_action: message_action_component,
    message_assistant: message_assistant_component,
    message_system: message_system_component,
    message_user: message_user_component,
    overlay_requires_settings: overlay_requires_settings_component,
    thread: thread_component
  }
};
