// AUTO-GENERATED by build_smart_env_config.js. DO NOT EDIT.
import { render as accept_deny_all_component } from '../src/components/accept_deny_all.js';
import { render as append_replace_component } from '../src/components/append_replace.js';
import { render as change_component } from '../src/components/change.js';
import { render as draft_creator_component } from '../src/components/draft_creator.js';
import { render as move_from_component } from '../src/components/move_from.js';
import { render as move_to_component } from '../src/components/move_to.js';

export const smart_env_config = {
  collections: {

  },
  item_types: {

  },
  components: {
    accept_deny_all: accept_deny_all_component,
    append_replace: append_replace_component,
    change: change_component,
    draft_creator: draft_creator_component,
    move_from: move_from_component,
    move_to: move_to_component
  }
};
